Dw 5066
dwp/aws-analytical-dataset-generation pull request #380
Opened 2020-10-05 08:45 UTC by abdu-n

Added section to generate_analytical_dataset_from_htme.py for saving correlation_id and s3_prefix to adg_params.csv
Added send_sn_message.py for sending ADG sending message
Added section for send_sns_message.py on step.tf
Added step to steps.yaml.tpl for send_snn_message.py
Output adg_completion_status_sns ARN from adg_completion_status_sns.tf

2020-10-05 09:00 UTC, sandeepg-github requested changes

2020-10-05 09:00 UTC, sandeepg-github commented on steps/generate_dataset_from_htme.py
> +def create_adg_status_csv(correlation_id, s3_prefix, publish_bucket, s3_client):
We would also need some unit tests for this. For reference I have written some tests in the branch attached to this ticket.

2020-10-05 09:11 UTC, TheDogfather17 requested changes

2020-10-05 09:18 UTC, abdu-n commented on steps/send_notification.py
> +    publish_bucket = "${publish_bucket}"
Tried publish_bucket = os.getenv("S3_PUBLISH_BUCKET"), it did not work, it returning none

2020-10-05 18:53 UTC, mattburgess reviewed
On top of what others have said, does this even need to be a separate step?

Does the driver process of the main PySpark script not keep track of whether its overall status is success or failure? Maybe we can get hold of that via a SparkListener (though my casual googling hasn't found a native PySpark interface to SparkListeners :( )

And now that I've asked that question, it occurs to me that this PR currently doesn't output a status at all, so consumers have no idea whether the run was successful or not and therefore whether the `s3_prefix` column points to a location with a partial dataset in it.

2020-10-05 20:47 UTC, mattburgess commented
> On top of what others have said, does this even need to be a separate step?
> 
> Does the driver process of the main PySpark script not keep track of whether its overall status is success or failure? Maybe we can get hold of that via a SparkListener (though my casual googling hasn't found a native PySpark interface to SparkListeners :( )
> 
> And now that I've asked that question, it occurs to me that this PR currently doesn't output a status at all, so consumers have no idea whether the run was successful or not and therefore whether the `s3_prefix` column points to a location with a partial dataset in it.

Looks like there's a `status` interface. There's an example at https://github.com/apache/spark/blob/master/examples/src/main/python/status_api_demo.py. API docs are at https://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.StatusTracker

2020-10-06 13:06 UTC, sandeepg-github commented on adg_params.csv
> +CORRELATION_ID,S3_PREFIX
this file needs deleted as it doesn't belong to source code

2020-10-06 17:49 UTC, TheDogfather17 approved these changes

2020-10-06 19:34 UTC, sandeepg-github approved these changes

2020-10-06 19:34 UTC, merged