add admin job to delete a dynamodb row using ci
dwp/aws-analytical-dataset-generation pull request #639
Opened 2021-03-24 14:22 UTC by TheDogfather17

Signed-off-by: levankirvalidze <levan.kirvalidze@dmwgroup.co.uk>

2021-03-24 16:08 UTC, steveburton4 commented
Can you add to the README please for what this does and how to use it. We should do this for all utility jobs we add (they are missing for now).

2021-03-24 16:08 UTC, steveburton4 requested changes

2021-03-24 16:08 UTC, steveburton4 commented on ci/jobs/preprod/admin/clear_dynamodb_row.yml
> +            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
```suggestion
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
```

2021-03-24 16:08 UTC, steveburton4 commented on ci/jobs/preprod/admin/clear_dynamodb_row.yml
> +            AWS_ACC: ((aws_account.development))
```suggestion
            AWS_ACC: ((aws_account.preprod))
```

2021-03-24 16:08 UTC, steveburton4 commented on ci/meta.yml
> +          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
Please remove this default line

2021-03-24 16:12 UTC, TheDogfather17 commented on ci/meta.yml
> +          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
that's done

2021-03-24 17:22 UTC, steveburton4 reviewed
README change still needed

2021-03-25 09:00 UTC, ChrisScottThomas approved these changes
LGTM

2021-03-25 09:06 UTC, steveburton4 approved these changes

2021-03-25 09:19 UTC, merged